// <auto-generated />
using System;
using GestionDeProductosYServicios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeProductosYServicios.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20241011001418_CreatedShipmentEntity")]
    partial class CreatedShipmentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Carrier", b =>
                {
                    b.Property<int>("Carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Carrier_id"));

                    b.Property<string>("Carrier_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_description");

                    b.Property<string>("Carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_name");

                    b.HasKey("Carrier_id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_description");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Client", b =>
                {
                    b.Property<int>("Client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Client_id"));

                    b.Property<string>("Client_address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_address");

                    b.Property<string>("Client_contact")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_contact");

                    b.Property<string>("Client_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_name");

                    b.HasKey("Client_id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment", b =>
                {
                    b.Property<int>("Shipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipments_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Shipment_id"));

                    b.Property<int>("Carrier_id")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<DateOnly?>("Shipment_arrival_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_arrival_date");

                    b.Property<DateOnly?>("Shipment_order_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_order_date");

                    b.Property<double>("Shipment_price_usa")
                        .HasColumnType("double")
                        .HasColumnName("shipments_price_usa");

                    b.Property<double>("Shipment_weight_kg")
                        .HasColumnType("double")
                        .HasColumnName("shipments_weight_kg");

                    b.HasKey("Shipment_id");

                    b.HasIndex("Carrier_id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment", b =>
                {
                    b.HasOne("GestionDeProductosYServicios.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("Carrier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });
#pragma warning restore 612, 618
        }
    }
}
