// <auto-generated />
using System;
using GestionDeProductosYServicios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeProductosYServicios.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20241011135512_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Carrier", b =>
                {
                    b.Property<int>("Carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Carrier_id"));

                    b.Property<string>("Carrier_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_description");

                    b.Property<string>("Carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_name");

                    b.HasKey("Carrier_id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_description");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Client", b =>
                {
                    b.Property<int>("Client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Client_id"));

                    b.Property<string>("Client_address")
                        .HasColumnType("longtext")
                        .HasColumnName("client_address");

                    b.Property<string>("Client_contact")
                        .HasColumnType("longtext")
                        .HasColumnName("client_contact");

                    b.Property<string>("Client_name")
                        .HasColumnType("longtext")
                        .HasColumnName("client_name");

                    b.HasKey("Client_id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Order", b =>
                {
                    b.Property<int>("Order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_id"));

                    b.Property<int>("Carrier_id")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<int>("Client_id")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateOnly?>("Order_creation_date")
                        .HasColumnType("date")
                        .HasColumnName("order_creation_date");

                    b.Property<DateOnly?>("Order_delivery_date")
                        .HasColumnType("date")
                        .HasColumnName("order_delivery_date");

                    b.HasKey("Order_id");

                    b.HasIndex("Carrier_id");

                    b.HasIndex("Client_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Product", b =>
                {
                    b.Property<int>("Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Product_id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Product_description")
                        .HasColumnType("longtext")
                        .HasColumnName("product_description");

                    b.Property<string>("Product_name")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<double>("Product_price")
                        .HasColumnType("double")
                        .HasColumnName("product_price");

                    b.HasKey("Product_id");

                    b.HasIndex("Category_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment", b =>
                {
                    b.Property<int>("Shipment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipments_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Shipment_id"));

                    b.Property<int>("Carrier_id")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<DateOnly?>("Shipment_arrival_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_arrival_date");

                    b.Property<DateOnly?>("Shipment_order_date")
                        .HasColumnType("date")
                        .HasColumnName("shipment_order_date");

                    b.Property<double>("Shipment_price_usa")
                        .HasColumnType("double")
                        .HasColumnName("shipments_price_usa");

                    b.Property<double>("Shipment_weight_kg")
                        .HasColumnType("double")
                        .HasColumnName("shipments_weight_kg");

                    b.HasKey("Shipment_id");

                    b.HasIndex("Carrier_id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment_Product", b =>
                {
                    b.Property<int>("Shipment_Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Shipment_Product_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Shipment_Product_id"));

                    b.Property<int>("Product_amount")
                        .HasColumnType("int")
                        .HasColumnName("product_amount");

                    b.Property<int>("Product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Shipment_id")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.HasKey("Shipment_Product_id");

                    b.HasIndex("Product_id");

                    b.HasIndex("Shipment_id");

                    b.ToTable("Shipments_Products");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Order", b =>
                {
                    b.HasOne("GestionDeProductosYServicios.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("Carrier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDeProductosYServicios.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Product", b =>
                {
                    b.HasOne("GestionDeProductosYServicios.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment", b =>
                {
                    b.HasOne("GestionDeProductosYServicios.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("Carrier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Shipment_Product", b =>
                {
                    b.HasOne("GestionDeProductosYServicios.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDeProductosYServicios.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("Shipment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shipment");
                });
#pragma warning restore 612, 618
        }
    }
}
