// <auto-generated />
using GestionDeProductosYServicios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeProductosYServicios.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20241010180307_createdCategoryFunction")]
    partial class createdCategoryFunction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Carrier", b =>
                {
                    b.Property<int>("Carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Carrier_id"));

                    b.Property<string>("Carrier_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_description");

                    b.Property<string>("Carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_name");

                    b.HasKey("Carrier_id");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_description");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
