// <auto-generated />
using GestionDeProductosYServicios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDeProductosYServicios.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20241010161139_CreatedNewSeeds")]
    partial class CreatedNewSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionDeProductosYServicios.Models.Carrier", b =>
                {
                    b.Property<int>("Carrier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Carrier_id"));

                    b.Property<string>("Carrier_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_description");

                    b.Property<string>("Carrier_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("carrier_name");

                    b.HasKey("Carrier_id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Carrier_id = 2,
                            Carrier_description = "Illum temporibus et ullam.",
                            Carrier_name = "Estel"
                        },
                        new
                        {
                            Carrier_id = 3,
                            Carrier_description = "Modi inventore provident optio qui.",
                            Carrier_name = "Lilian"
                        },
                        new
                        {
                            Carrier_id = 4,
                            Carrier_description = "Quas minus est eligendi aspernatur omnis nesciunt modi.",
                            Carrier_name = "Emilia"
                        },
                        new
                        {
                            Carrier_id = 5,
                            Carrier_description = "Fugit aut aut.",
                            Carrier_name = "Oleta"
                        },
                        new
                        {
                            Carrier_id = 6,
                            Carrier_description = "Facere exercitationem est aperiam.",
                            Carrier_name = "Abby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
